# Generated by Django 3.1.7 on 2021-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_title', models.CharField(max_length=30)),
                ('e_content', models.CharField(max_length=300)),
                ('e_image', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='image',
            field=models.URLField(default='NULL'),
        ),
    ]
